# Digital Ocean App Platform Configuration
# Deploy Year Grid Calendar as a web service

name: year-grid-calendar

# Services
services:
  - name: web
    # Build from Dockerfile
    dockerfile_path: Dockerfile.do

    # Source code
    github:
      # Replace with your repo details
      repo: ceesaxp/year-grid-calendar
      branch: main
      deploy_on_push: true

    # Or use GitLab
    # gitlab:
    #   repo: your--username/year-grid-calendar
    #   branch: main
    #   deploy_on_push: true

    # Run configuration
    run_command: uvicorn web.app:app --host 0.0.0.0 --port 8080

    # Environment variables
    envs:
      - key: PORT
        value: "8080"
      - key: PYTHONUNBUFFERED
        value: "1"
      - key: TZ
        value: "UTC"

    # HTTP configuration
    http_port: 8080

    # Health check
    health_check:
      http_path: /health
      initial_delay_seconds: 10
      period_seconds: 30
      timeout_seconds: 10
      success_threshold: 1
      failure_threshold: 3

    # Instance size
    # Options: basic-xxs, basic-xs, basic-s, basic-m, professional-xs, professional-s, professional-m
    instance_size_slug: basic-xs
    instance_count: 1

    # Auto-scaling (optional)
    # autoscaling:
    #   min_instance_count: 1
    #   max_instance_count: 3
    #   metrics:
    #     cpu:
    #       percent: 80

    # Routes
    routes:
      - path: /

# Domain configuration
domains:
  - domain: year-grid.ceesaxp.org
    type: PRIMARY
    zone: ceesaxp.org

# Region
region: nyc

# Alerts (optional)
alerts:
  - rule: DEPLOYMENT_FAILED
  - rule: DOMAIN_FAILED

# Features
features:
  - buildpack-stack=ubuntu-22
# Static outbound IP (Professional plan only)
# ingress:
#   rules:
#     - component:
#         name: web
#       match:
#         path:
#           prefix: /
